version: '{build}'

services:
- mssql2014
- iis
configuration:
- Debug
platform: Any CPU
environment:
  DatabaseSettings__ConnectionString: Server=(local)\SQL2014;Initial Catalog=TestDatabase;User ID=sa;Password=Password12!;MultipleActiveResultSets=true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\ContinuousIntegration.Api" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\ContinuousIntegration" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\ContinuousIntegration.Web" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\ContinuousIntegration.Api" -c Debug --no-build --version-suffix %LABEL% -o .\artifacts
- dotnet pack "src\ContinuousIntegration" -c Debug --no-build --version-suffix %LABEL% -o .\artifacts
- dotnet publish "src\ContinuousIntegration.Web" -c Debug --no-build --framework netcoreapp1.0 -o %appveyor_build_folder%\publish
test_script:
- dotnet test "test\ContinuousIntegrationUnitTests" -c %CONFIGURATION%
before_deploy: PowerShell .\InstallSelfSignedCert.ps1
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\publish
  name: ContinuousIntegration.Web
  type: WebDeployPackage
deploy:
  # Local deployment for testing
  - provider: Local
    artifact: ContinuousIntegration.Web
    ContinuousIntegration.Web.deploy_website: true
    ContinuousIntegration.Web.site_name: Default Web Site
    ContinuousIntegration.Web.remove_files: true
after_deploy:
- dotnet test "test\ContinuousIntegration.IntegrationTests" -c %CONFIGURATION%