version: '{build}'

services:
- mssql2014
configuration:
- Debug
platform: Any CPU
environment:
  DatabaseSettings__ConnectionString: Server=(local)\SQL2014;Initial Catalog=TestDatabase;User ID=sa;Password=Password12!;MultipleActiveResultSets=true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\ContinuousIntegration" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
test_script:
- dotnet test "test\ContinuousIntegrationUnitTests" -c %CONFIGURATION%
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet