version: '{build}'

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
environment:
  DatabaseSettings__ConnectionString: Server=(local)\SQL2014;Initial Catalog=TestDatabase;User ID=sa;Password=Password12!;MultipleActiveResultSets=true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
services:
- mssql2014
- iis
configuration:
- Debug
platform: Any CPU
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\ContinuousIntegration.Api" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\ContinuousIntegration" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\ContinuousIntegration.Web" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\ContinuousIntegration.Api" -c Debug --no-build --version-suffix %LABEL% -o .\artifacts
- dotnet pack "src\ContinuousIntegration" -c Debug --no-build --version-suffix %LABEL% -o .\artifacts
- dotnet publish "src\ContinuousIntegration.Web" -c Debug --no-build --framework netcoreapp1.0 -o %appveyor_build_folder%\publish
- '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="%appveyor_build_folder%\publish\ContinuousIntegration.Web.zip" -dest:auto,-setParam:"IIS Web Application Name"="Default Web Site"'
test_script:
- dotnet test "test\ContinuousIntegrationUnitTests" -c %CONFIGURATION%
before_deploy: PowerShell .\InstallSelfSignedCert.ps1
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\publish
  name: ContinuousIntegration.Web
  type: WebDeployPackage
deploy:
  # Local deployment for testing
after_deploy:
- dotnet test "test\ContinuousIntegration.IntegrationTests" -c %CONFIGURATION%